ExternalProject_Add(SFML 
	GIT_REPOSITORY https://github.com/SFML/SFML.git
    GIT_TAG 2.5.1 
    CMAKE_ARGS 
		-DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/lib
        -DSFML_BUILD_WINDOW=TRUE
        -DSFML_BUILD_GRAPHICS=TRUE
        -DSFML_BUILD_AUDIO=FALSE
        -DSFML_BUILD_NETWORK=FALSE
        -DSFML_BUILD_SYSTEM=FALSE
        -DSFML_BUILD_TEST_SUITE=FALSE
        -DBUILD_EXAMPLES=FALSE
        -DBUILD_SHARED_LIBS=TRUE
)
