name: Check Build

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  linux-test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -e
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Check Files
        run: |
          set -e
          ls -l raytracer

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Download SFML library
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip -OutFile SFML-2.5.1-windows-vc15-64-bit.zip
          Expand-Archive SFML-2.5.1-windows-vc15-64-bit.zip -DestinationPath SFML
      - name: Add SFML to PATH
        shell: powershell
        run: |
          $env:Path = "C:\SFML\bin;" + $env:Path
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Release
          cd ..
      - name: Check Files
        run: |
          ls -l raytracer.exe
