name: Check Build

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'

jobs:
  linux-test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
      - name: install-Libconfig++
        run: |
          sudo dnf install -y libconfig-devel
      - name: Build
        run: |
          set -e
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Check Files
        run: |
          set -e
          ls -l raytracer

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Release
          cd ..
      - name: Check Files
        run: |
          ls -l raytracer.exe
